#Requires -RunAsAdministrator
#Requires -Version 7.0
<#
.SYNOPSIS
    SOK-FUTURE v1.1.0 — The Architect & Guardian
    Temporal Domain: Proactive Protection, Data Continuity, Disaster Resilience

.DESCRIPTION
    SOK-FUTURE is the third of three temporal meta-scripts. It consolidates three
    scripts that all answer one operational question: "How do we ensure this machine
    survives the next hardware failure, storage crisis, or accidental deletion?"

    WHY THIS TEMPORAL SLICE?
    These three modules look FORWARD. They are not reactive (like PRESENT) or
    retrospective (like PAST). They are entirely proactive: building the junctions
    that prevent C: from filling up BEFORE it happens, backing up the projects that
    will be needed if Git corrupts BEFORE that happens, and archiving the code that
    would otherwise be unrecoverable if the SSD dies TODAY.

    The Substrate Thesis (documented in SOK-FamilyPicture.ps1) states:
    "If your laptop's motherboard fries tomorrow, you don't lose your environment.
    You plug your E: drive into a new machine, run SOK-BareMetal to rebuild your
    brain, and run SOK-BackupRestructure to rebuild your memory."
    SOK-FUTURE is what makes that sentence true.

    INTEGRATED MODULES:
    1. Offload  — Move heavy toolchain directories to E: and replace with NTFS junctions
    2. Backup   — Robocopy mirroring of Projects to E:\Backup_Archive
    3. Archive  — Stream source code snapshots to versioned flat-file .txt archives

    DATA FLOW FROM SOK-PAST:
    SOK-FUTURE consumes artifacts generated by SOK-PAST:
    - Offload reads the latest SOK-Inventory JSON to know which junctions already
      exist (avoiding redundant offload operations).
    - Offload can also consume GlobalState['SpaceAudit_Offloadable'] directly if
      SOK-PAST ran in the same process (future BOC integration scenario).
    - If no Inventory JSON exists, Offload operates from its hardcoded target list.

    FULL DISCLOSURE (PROGRESSIVE ENCLOSURE):
    By default this script runs ALL three modules (Offload, Backup, Archive). Use -Skip*
    flags to narrow the default run. Opt-in flags still work (backward compatible).
    -All forces all three regardless of -Skip* flags.
    Offload moves GBs of data — always use -DryRun on first run or new machines.
    -Incremental (/MIR) is always-explicit: NEVER in scheduled/unattended runs.

    TYPICAL CADENCE:
    After C: fills      : .\SOK-FUTURE.ps1 -Offload -DryRun  (then without -DryRun)
    Nightly protection  : .\SOK-FUTURE.ps1 -Backup -Incremental
    Before git push     : .\SOK-FUTURE.ps1 -Archive
    Full proactive run  : .\SOK-FUTURE.ps1 -All -DryRun
    Production full run : .\SOK-FUTURE.ps1 -Backup -Incremental -Archive

.EXAMPLE
    .\SOK-FUTURE.ps1 -Offload -ExternalDrive E: -DryRun
    Preview which directories would be offloaded to E: without making changes.

.EXAMPLE
    .\SOK-FUTURE.ps1 -Backup -BackupSources "C:\Users\shelc\Documents\Journal\Projects" -Incremental
    Incremental mirror backup of Projects to E:\Backup_Archive using robocopy /MIR.

.EXAMPLE
    .\SOK-FUTURE.ps1 -Archive -ArchiveSources "C:\Users\shelc\Documents\Journal\Projects\SOK" -DryRun
    Preview source code archival without writing the archive file.

.EXAMPLE
    .\SOK-FUTURE.ps1 -All
    Run full FUTURE suite: offload heavy dirs, mirror backup, archive source code.
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    # ── GLOBAL ─────────────────────────────────────────────────────────────────
    # DryRun is especially important here — Offload MOVES files. Always preview first.
    [switch]$DryRun,

    # ── MODULE ACTIVATION (opt-in, backward compat) ───────────────────────────
    # If NONE of these are set, default is full-run (progressive enclosure).
    # Use -Skip* flags to narrow the default. -DryRun strongly recommended on first run.
    [switch]$Offload,    # SOK-Offload:  move heavy dirs to E:\ and replace with junctions
    [switch]$Backup,     # SOK-Backup:   robocopy /E backup to E:\Backup_Archive (additive)
    [switch]$Archive,    # SOK-Archiver: stream source code snapshots to versioned .txt
    # -All: force all three modules regardless of -Skip* flags.
    [switch]$All,
    # ── MODULE SKIP (progressive enclosure) ───────────────────────────────────
    # Narrow the default full run. Only applies when no opt-in flags are set.
    [switch]$SkipOffload,  # Exclude Offload from default run
    [switch]$SkipBackup,   # Exclude Backup from default run
    [switch]$SkipArchive,  # Exclude Archive from default run

    # ── OFFLOAD PARAMS ─────────────────────────────────────────────────────────
    # The drive where SOK_Offload directories live.
    [string]$ExternalDrive = 'E:',
    # If provided, skip auto-detection and use this specific Inventory JSON.
    # If omitted, Offload looks for the latest SOK-Inventory JSON via Get-LatestLog.
    [string]$InventoryPath,
    # Only offload directories larger than this threshold. Default ~20MB.
    # Prevents fragmenting the E: drive with tiny directories.
    [int]$MinSizeKB = 21138,
    # Maximum allowed utilization on E: before Offload refuses to add more.
    # 96% matches the MAX_UTILIZATION_PCT constant in SOK-Common.
    [int]$MaxDriveUtilPct = 96,

    # ── BACKUP PARAMS ──────────────────────────────────────────────────────────
    # Source directories to mirror. Default: the full Projects tree.
    [string[]]$BackupSources = @("$env:USERPROFILE\Documents\Journal\Projects"),
    # Destination on the external drive.
    [string]$BackupDest = 'E:\Backup_Archive',
    # Default (omit flag): uses /E — additive only. NEVER deletes from dest. Safe nightly default.
    # -Incremental: uses /MIR — two-way sync. DELETES from dest when source files are absent.
    # NEVER pass -Incremental in scheduled/unattended contexts.
    [switch]$Incremental,
    # Thread count for robocopy /MT. Tuned for i7-13700H.
    [int]$Threads = 13,

    # ── ARCHIVER PARAMS ────────────────────────────────────────────────────────
    # Source directories to include in the archive snapshot.
    [string[]]$ArchiveSources = @(
        "$env:USERPROFILE\Documents\Journal\Projects\SOK",
        "$env:USERPROFILE\Documents\Journal\Projects\scripts"
    ),
    # Base name for the output file. Auto-increments: SOK_Archive_v1.txt, v2.txt, ...
    [string]$ArchiveBaseName = 'SOK_Archive',
    # Output directory for archive files.
    [string]$ArchiveOutputDir = "$env:USERPROFILE\Documents\Journal\Projects\SOK\Archives",
    # Regex matching file extensions to include in the archive.
    # Excludes binary, media, and compiled files — captures only human-readable source.
    [string]$ArchiveExtensions = '(?i)\.(txt|md|ps1|psm1|psd1|py|json|log|yaml|yml|xml|conf|ini|sh|bat|css|js|jsx|ts|tsx|sql|toml|cfg|r|go|rs)$'
)

# ══════════════════════════════════════════════════════════════════════════════
# [0] CORE INITIALIZATION
# ══════════════════════════════════════════════════════════════════════════════
$ErrorActionPreference = 'Continue'
$GlobalStartTime       = Get-Date

$modulePath = Join-Path $PSScriptRoot 'common\SOK-Common.psm1'
if (-not (Test-Path $modulePath)) {
    $modulePath = 'C:\Users\shelc\Documents\Journal\Projects\scripts\common\SOK-Common.psm1'
}
if (Test-Path $modulePath) {
    Import-Module $modulePath -Force
} else {
    Write-Error "CRITICAL: SOK-Common.psm1 not found."
    exit 1
}

$logPath = Initialize-SOKLog -ScriptName 'SOK-FUTURE'
$config  = Get-SOKConfig

# ── Full Disclosure / Progressive Enclosure gate ─────────────────────────────
# Default: run all three modules. -Skip* flags narrow the default.
# Explicit opt-in flags run only those (backward compat). -All forces all.
$anyOptIn = $Offload.IsPresent -or $Backup.IsPresent -or $Archive.IsPresent

if ($All) {
    $Offload = $Backup = $Archive = $true
} elseif (-not $anyOptIn) {
    if (-not $SkipOffload)  { $Offload  = $true }
    if (-not $SkipBackup)   { $Backup   = $true }
    if (-not $SkipArchive)  { $Archive  = $true }
}

$ActiveModules = @()
if ($Offload) { $ActiveModules += 'Offload' }
if ($Backup)  { $ActiveModules += "Backup[$(if($Incremental){'Incremental'}else{'/E'})]" }
if ($Archive) { $ActiveModules += 'Archive' }

if ($ActiveModules.Count -eq 0) {
    Write-SOKLog 'All modules skipped via -Skip* flags. Nothing to run.' -Level Warn
    exit 0
}

Show-SOKBanner -ScriptName 'SOK-FUTURE' -Subheader "Active: $($ActiveModules -join ' | ')$(if ($DryRun) {' [DRY RUN]'})"
Write-SOKLog "Temporal Domain: FUTURE — Proactive Protection, Junction Architecture, Data Continuity" -Level Section

$GlobalState = New-SOKStateDict

try {
# ══════════════════════════════════════════════════════════════════════════════
# [1] OFFLOAD — Move Heavy Toolchains to E:\ + Replace with NTFS Junctions
# ══════════════════════════════════════════════════════════════════════════════
# The Offload module is the primary mechanism for preventing C: drive storage
# crises. Instead of simply copying files to E:, it MOVES them (robocopy /MOVE)
# and then creates an NTFS junction (mklink /J) at the original path.
# To every application on the system, the path is identical — they read and
# write through the junction transparently. The data lives on E:, but
# C:\Users\shelc\.pyenv still works perfectly from the application's perspective.
#
# THE 23-TARGET HIERARCHY:
# Targets are organized into 7 priority tiers. P1 (Docker/WSL2 VM disk) can be
# 50+ GB alone. P2 (databases) frees RAM-resident storage. P3-P7 cover runtimes,
# caches, IDEs, and miscellaneous. The 96% budget ceiling prevents the E: drive
# from approaching full — a full E: breaks all existing junctions simultaneously.
#
# SAFETY GUARDS:
# - Never offload to an already-junction source (would create circular reference)
# - Never offload paths matching $rxNeverMove (Windows internals)
# - Respect 96% budget ceiling on E:
# - Robocopy exit code >= 8 = error, junction is NOT created
# - Always -DryRun first on a live machine
if ($Offload) {
    Write-SOKLog "━━━ [1] OFFLOAD: Junction Architecture ($ExternalDrive) ━━━" -Level Section
    if ($DryRun) { Write-SOKLog '*** DRY RUN — no files will be moved ***' -Level Warn }

    # `goto` does not exist in PowerShell. Early-exit from a non-loop block uses
    # the do { } while ($false) + break idiom: the do block runs exactly once,
    # and break exits it immediately — functionally identical to goto endOffload.
    do {

    # ── Validate external drive ──────────────────────────────────────────────
    if (-not (Test-Path "$ExternalDrive\")) {
        Write-SOKLog "External drive $ExternalDrive not found. Verify drive is mounted." -Level Error
        break
    }
    $extDisk = Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='$ExternalDrive'" -ErrorAction SilentlyContinue
    if (-not $extDisk) { Write-SOKLog "Cannot read $ExternalDrive disk info." -Level Error; break }

    $extFreeKB  = [math]::Round($extDisk.FreeSpace / 1KB, 0)
    $extTotalKB = [math]::Round($extDisk.Size / 1KB, 0)
    $extUsedPct = [math]::Round((($extDisk.Size - $extDisk.FreeSpace) / $extDisk.Size) * 100, 1)
    Write-SOKLog "${ExternalDrive}: $([math]::Round($extFreeKB/1MB,1)) GB free / $([math]::Round($extTotalKB/1MB,1)) GB total ($extUsedPct% used)" -Level $(if ($extUsedPct -gt 85) {'Warn'} else {'Ignore'})

    if ($extUsedPct -ge $MaxDriveUtilPct) {
        Write-SOKLog "ABORT: $ExternalDrive is at $extUsedPct% — at or above $MaxDriveUtilPct% budget ceiling. No offloads possible." -Level Error
        break
    }

    # ── E: drive health check (before touching anything) ────────────────────
    # Refuse to offload onto a degraded drive — that would move data off a good C:
    # onto a failing E:, which is worse than doing nothing.
    $physDisks = Get-PhysicalDisk -ErrorAction SilentlyContinue
    $extVolume = Get-Volume -DriveLetter ($ExternalDrive.TrimEnd(':')) -ErrorAction SilentlyContinue
    if ($extVolume -and $extVolume.HealthStatus -ne 'Healthy') {
        Write-SOKLog "ABORT: $ExternalDrive volume health is '$($extVolume.HealthStatus)'. Refusing to offload onto degraded drive." -Level Error
        break
    }

    # Offload root directory on E:
    $offloadRoot = Join-Path $ExternalDrive 'SOK_Offload'
    if (-not $DryRun -and -not (Test-Path $offloadRoot)) { New-Item -Path $offloadRoot -ItemType Directory -Force | Out-Null }

    # ── Safety regex — never move these ─────────────────────────────────────
    $rxNeverMove = [regex]::new('(?ix)^[A-Z]:\\Windows|^[A-Z]:\\Recovery|\\(System32|SysWOW64|WinSxS|pagefile|hiberfil)([\\]|$)|^[A-Z]:\\Users$|\.git\\objects', [System.Text.RegularExpressions.RegexOptions]::Compiled)

    # ── 23-target offload list — 7-tier priority ─────────────────────────────
    # Each entry: Source path, DepGroup (for display), Priority (1=highest)
    # Priority 1 targets are offloaded first to maximize space freed per operation.
    $offloadTargets = @(
        # P1: Docker/WSL2 — largest single items on the drive
        @{ Source = "$env:LOCALAPPDATA\Docker\wsl";                      Group = 'P1-Docker'; Priority = 1; Desc = 'Docker WSL2 VM disk (ext4.vhdx) — can be 30-60 GB' }
        # P2: Databases — frees RAM + disk simultaneously (data dirs)
        @{ Source = 'C:\Program Files\PostgreSQL\15\data';               Group = 'P2-Database'; Priority = 2; Desc = 'PostgreSQL 15 data dir' }
        @{ Source = 'C:\Program Files\MongoDB\Server\7.0\data';          Group = 'P2-Database'; Priority = 2; Desc = 'MongoDB data dir' }
        @{ Source = 'C:\Program Files\Neo4j\data';                       Group = 'P2-Database'; Priority = 2; Desc = 'Neo4j graph data' }
        # P3: Runtimes — pyenv, conda, scoop apps
        @{ Source = "$env:USERPROFILE\.pyenv";                           Group = 'P3-Runtime'; Priority = 3; Desc = 'Python version manager environments' }
        @{ Source = "$env:USERPROFILE\.conda\envs";                      Group = 'P3-Runtime'; Priority = 3; Desc = 'Conda virtual environments' }
        @{ Source = "$env:USERPROFILE\scoop\apps";                       Group = 'P3-Runtime'; Priority = 3; Desc = 'Scoop app binaries' }
        @{ Source = "$env:LOCALAPPDATA\Programs\miniconda3\pkgs";        Group = 'P3-Runtime'; Priority = 3; Desc = 'Miniconda package cache' }
        # P4: Build/package caches
        @{ Source = 'C:\ProgramData\chocolatey\lib';                     Group = 'P4-Cache'; Priority = 4; Desc = 'Chocolatey installed packages lib' }
        @{ Source = "$env:USERPROFILE\.cargo\registry";                  Group = 'P4-Cache'; Priority = 4; Desc = 'Cargo crate registry cache' }
        @{ Source = "$env:USERPROFILE\.nuget\packages";                  Group = 'P4-Cache'; Priority = 4; Desc = '.NET NuGet packages cache' }
        @{ Source = "$env:APPDATA\npm\node_modules";                     Group = 'P4-Cache'; Priority = 4; Desc = 'NPM global modules' }
        @{ Source = "$env:USERPROFILE\.gradle\caches";                   Group = 'P4-Cache'; Priority = 4; Desc = 'Gradle build cache' }
        # P5: Large app data
        @{ Source = "$env:LOCALAPPDATA\Packages\Insomnia.Insomnia_*";   Group = 'P5-AppData'; Priority = 5; Desc = 'Insomnia app data' }
        @{ Source = "$env:APPDATA\GitKraken";                            Group = 'P5-AppData'; Priority = 5; Desc = 'GitKraken app data + logs' }
        @{ Source = "$env:APPDATA\Logseq";                               Group = 'P5-AppData'; Priority = 5; Desc = 'Logseq IndexedDB + workspace cache' }
        @{ Source = "$env:LOCALAPPDATA\GitHubDesktop";                   Group = 'P5-AppData'; Priority = 5; Desc = 'GitHub Desktop app-* update dirs' }
        @{ Source = "$env:APPDATA\Postman";                              Group = 'P5-AppData'; Priority = 5; Desc = 'Postman app + package cache' }
        # P6: IDEs
        @{ Source = "$env:LOCALAPPDATA\JetBrains";                      Group = 'P6-IDE'; Priority = 6; Desc = 'JetBrains IDE local app data' }
        @{ Source = "C:\Program Files\JetBrains";                        Group = 'P6-IDE'; Priority = 6; Desc = 'JetBrains IDE installations' }
        @{ Source = "$env:USERPROFILE\.vscode\extensions";               Group = 'P6-IDE'; Priority = 6; Desc = 'VS Code extensions' }
        # P7: Misc large dirs
        @{ Source = 'C:\tools\flutter';                                  Group = 'P7-Misc'; Priority = 7; Desc = 'Flutter SDK' }
        @{ Source = "$env:USERPROFILE\AppData\Local\Microsoft\WinGet\Packages"; Group = 'P7-Misc'; Priority = 7; Desc = 'WinGet installed packages cache' }
    )

    # ── Try to load Inventory for context ────────────────────────────────────
    # IMPORTANT: Get-LatestLog returns a [PSCustomObject] {Path, Name, Age, Data} — not a path string.
    # Get-LatestLogPath (Common v4.4.0+) unwraps .Path so Test-Path works correctly.
    $inventoryJson = $null
    $resolvedInvPath = $InventoryPath
    if (-not $resolvedInvPath) {
        # Use Get-LatestLog (not just path) so we can check the age of the log.
        $latestInv = Get-LatestLog -ScriptName 'SOK-Inventory'
        if ($latestInv) {
            $resolvedInvPath = $latestInv.Path
            # Warn if the log is older than 24 hours — may be from a prior era.
            if ($latestInv.Age.TotalHours -gt 24) {
                Write-SOKLog ("Inventory log is {0:F1}h old (>24h). Junction context may be stale." -f $latestInv.Age.TotalHours) -Level Warn
                Write-SOKLog "  Run SOK-PAST -TakeInventory to generate a fresh snapshot." -Level Warn
                Write-SOKLog "  Or pass -InventoryPath <path> to specify a log explicitly." -Level Warn
            } else {
                Write-SOKLog ("Inventory log age: {0:F1}h — fresh" -f $latestInv.Age.TotalHours) -Level Ignore
            }
        }
    }
    if ($resolvedInvPath -and (Test-Path $resolvedInvPath)) {
        try {
            $inventoryJson = Get-Content $resolvedInvPath -Raw | ConvertFrom-Json -ErrorAction SilentlyContinue
            Write-SOKLog "Inventory loaded: $resolvedInvPath" -Level Ignore
        } catch { Write-SOKLog "Could not parse inventory JSON. Proceeding without." -Level Warn }
    } else { Write-SOKLog "No inventory JSON found. Run SOK-PAST -TakeInventory first for richer context." -Level Warn }

    # ── Execute offloads ──────────────────────────────────────────────────────
    $offloaded = 0; $skipped = 0; $failed = 0

    # Running free-bytes tally: tracks E: free space as we offload.
    # CRITICAL: do NOT use $extDisk.FreeSpace for per-item budget checks inside the loop —
    # that value is stale (captured at script start). After offloading a 40GB Docker WSL2 vhdx,
    # the budget check for the next item would still think E: has the original free space,
    # potentially approving an offload that pushes E: past the 96% ceiling.
    $runningFreeBytes = $extDisk.FreeSpace

    foreach ($target in ($offloadTargets | Sort-Object Priority)) {
        # Resolve wildcard paths (Insomnia uses versioned folder names)
        $resolvedSrc = if ($target.Source -match '\*') {
            $candidates = @(Get-Item $target.Source -ErrorAction SilentlyContinue | Select-Object -First 1)
            if ($candidates) { $candidates[0].FullName } else { $null }
        } else { $target.Source }

        if (-not $resolvedSrc -or -not (Test-Path $resolvedSrc)) {
            Write-SOKLog "  SKIP (not found): $($target.Source)" -Level Ignore; $skipped++; continue
        }

        # Safety: never offload Windows-critical paths
        if ($rxNeverMove.IsMatch($resolvedSrc)) {
            Write-SOKLog "  SKIP (protected): $resolvedSrc" -Level Warn; $skipped++; continue
        }

        # Safety: skip already-junctioned (would create a dangling chain)
        $srcAttr = [System.IO.File]::GetAttributes($resolvedSrc)
        if (($srcAttr -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            $existingTarget = ([System.IO.DirectoryInfo]::new($resolvedSrc)).LinkTarget
            Write-SOKLog "  SKIP (already junction -> $existingTarget): $resolvedSrc" -Level Ignore; $skipped++; continue
        }

        # Calculate size
        $sizeKB = 0
        try {
            $fo = [System.IO.EnumerationOptions]::new(); $fo.IgnoreInaccessible = $true; $fo.RecurseSubdirectories = $true
            foreach ($f in [System.IO.Directory]::EnumerateFiles($resolvedSrc, '*', $fo)) {
                try { $sizeKB += [math]::Round((New-Object System.IO.FileInfo($f)).Length / 1KB, 0) } catch { }
            }
        } catch { }

        if ($sizeKB -lt $MinSizeKB) {
            Write-SOKLog "  SKIP (too small, $([math]::Round($sizeKB/1MB,1)) GB < threshold): $resolvedSrc" -Level Ignore; $skipped++; continue
        }

        # Budget check using RUNNING tally (not stale $extDisk.FreeSpace from script start).
        # Each successful offload subtracts from $runningFreeBytes so subsequent items see
        # the true remaining capacity on E:.
        $projectedUsedBytes = $extDisk.Size - $runningFreeBytes + ($sizeKB * 1KB)
        $projectedPct = [math]::Round(($projectedUsedBytes / $extDisk.Size) * 100, 1)
        if ($projectedPct -gt $MaxDriveUtilPct) {
            Write-SOKLog "  SKIP (budget: $projectedPct% would exceed ${MaxDriveUtilPct}%): $resolvedSrc ($([math]::Round($sizeKB/1MB,1)) GB)" -Level Warn; $skipped++; continue
        }

        # Derive destination path: drive letter and separators → underscores
        $relative = ($resolvedSrc -replace '^([A-Z]):', '$1') -replace '[\\]', '_'
        $destPath = Join-Path $offloadRoot $relative

        Write-SOKLog "  [$($target.Priority)] $resolvedSrc ($([math]::Round($sizeKB/1MB,1)) GB) — $($target.Desc)" -Level Warn

        if ($DryRun) {
            Write-SOKLog "  [DRY] Would offload: $resolvedSrc -> $destPath" -Level Ignore; $skipped++; continue
        }

        # Execute: robocopy /MOVE, then mklink /J
        if (-not (Test-Path $destPath)) { New-Item -Path $destPath -ItemType Directory -Force | Out-Null }
        $roboArgs = @($resolvedSrc, $destPath, '/E', '/MOVE', '/R:3', '/W:5', "/MT:$Threads", '/XJ', '/COPY:DAT', '/DCOPY:T', '/NFL', '/NDL', '/NP')
        $roboOutput = & robocopy @roboArgs 2>&1
        $roboExit   = $LASTEXITCODE

        if ($roboExit -lt 8) {
            # Robocopy succeeded — source is now empty, safe to remove and junction
            if (Test-Path $resolvedSrc) { Remove-Item $resolvedSrc -Recurse -Force -ErrorAction SilentlyContinue }
            $junctionResult = cmd /c "mklink /J `"$resolvedSrc`" `"$destPath`"" 2>&1
            if ($LASTEXITCODE -eq 0) {
                # Post-offload junction verification: confirm the junction resolves correctly.
                # A junction that exists syntactically but points to a missing target is silent
                # corruption — applications would fail with cryptic path errors later.
                $jxnAttr = [System.IO.File]::GetAttributes($resolvedSrc) -band [System.IO.FileAttributes]::ReparsePoint
                $jxnTarget = ([System.IO.DirectoryInfo]::new($resolvedSrc)).LinkTarget
                if ($jxnAttr -ne 0 -and $jxnTarget -and (Test-Path $jxnTarget)) {
                    Write-SOKLog "  Junction verified: $resolvedSrc -> $destPath" -Level Success
                } else {
                    Write-SOKLog "  WARN: Junction created but verification failed (target: $jxnTarget)" -Level Error
                }
                $offloaded++
                # Deduct from running free-bytes so next iteration's budget check is accurate
                $runningFreeBytes -= ($sizeKB * 1KB)
            } else {
                Write-SOKLog "  WARN: robocopy OK but junction failed: $junctionResult" -Level Error; $failed++
            }
        } else {
            Write-SOKLog "  ERROR: robocopy exit $roboExit for $resolvedSrc" -Level Error; $failed++
        }
    }

    # Final E: utilization after all offloads
    $finalUsedPct = [math]::Round((($extDisk.Size - $runningFreeBytes) / $extDisk.Size) * 100, 1)
    Write-SOKLog "Offload complete. Moved: $offloaded | Skipped: $skipped | Failed: $failed | E: utilization now ~$finalUsedPct%" -Level Success
    Save-SOKHistory -ScriptName 'SOK-Offload' -RunData @{ Offloaded=$offloaded; Skipped=$skipped; Failed=$failed; DryRun=$DryRun.IsPresent; FinalDriveUtilPct=$finalUsedPct }

    } while ($false)  # do { } while ($false) — paired with break statements above for early-exit
}

# ══════════════════════════════════════════════════════════════════════════════
# [2] BACKUP — Robocopy Mirror to E:\Backup_Archive
# ══════════════════════════════════════════════════════════════════════════════
# Backup is conceptually simple: use robocopy to maintain a copy of Projects
# on E:. The design decisions are in the flags:
#
#   /MIR (Incremental=true)  — Two-way sync. Files deleted from source are
#                               deleted from dest. Keeps E: clean; use for nightly.
#   /E (Incremental=false)   — Additive only. Never deletes from dest. Use for
#                               first-time copies or forensic preservation.
#   /XJ                      — Exclude junctions. CRITICAL: without this, robocopy
#                               would traverse every junction on C: as if it were
#                               a real directory, potentially copying the ENTIRE E:
#                               drive back onto itself.
#   /COPY:DAT                — Copy Data+Attributes+Timestamps (not security ACLs
#                               which can cause cross-machine permission issues)
#   /R:3 /W:5                — 3 retries with 5-second wait (handles locked files)
#
# VERIFICATION:
# After each source, robocopy exit code is evaluated. Exit < 4 = clean success.
# File count + size deltas are checked: > 5 files OR > 1% size difference = WARN.
if ($Backup) {
    Write-SOKLog "━━━ [2] BACKUP: Robocopy $(if($Incremental){'Mirror (Incremental)'}else{'Full Copy'}) ━━━" -Level Section
    Write-SOKLog "Sources: $($BackupSources.Count) | Dest: $BackupDest | Threads: $Threads" -Level Ignore
    if ($DryRun) { Write-SOKLog '*** DRY RUN — robocopy /L mode (list only) ***' -Level Warn }

    # Validate backup destination drive has space
    $destDrive = ($BackupDest -split ':')[0] + ':'
    $destDisk  = Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='$destDrive'" -ErrorAction SilentlyContinue
    if ($destDisk) {
        $destFreeKB = [math]::Round($destDisk.FreeSpace / 1KB, 0)
        Write-SOKLog "Destination drive ${destDrive}: $destFreeKB KB free" -Level $(if ($destFreeKB -lt 10485760) {'Warn'} else {'Ignore'})
    }

    if (-not $DryRun -and -not (Test-Path $BackupDest)) {
        New-Item -Path $BackupDest -ItemType Directory -Force | Out-Null
    }

    $totalCopied = 0; $totalFailed = 0; $allVerified = $true
    $roboFlag    = if ($Incremental) { '/MIR' } else { '/E' }

    foreach ($src in $BackupSources) {
        if (-not (Test-Path $src)) {
            Write-SOKLog "SOURCE NOT FOUND: $src" -Level Error; $totalFailed++; continue
        }
        $srcName  = Split-Path $src -Leaf
        $destPath = Join-Path $BackupDest $srcName
        $logFile  = Join-Path (Get-ScriptLogDir -ScriptName 'SOK-Backup') "robo_${srcName}_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

        Write-SOKLog "Backing up: $src -> $destPath" -Level Ignore

        $roboArgs = @(
            $src, $destPath, $roboFlag,
            '/R:3', '/W:5', "/MT:$Threads",
            '/XJ',           # CRITICAL: exclude junctions (prevents recursion disaster)
            '/COPY:DAT', '/DCOPY:T',
            '/NP', '/ETA', '/BYTES',
            "/LOG+:$logFile"
        )
        if ($DryRun) { $roboArgs += '/L' }

        $roboOutput = & robocopy @roboArgs 2>&1
        $roboExit   = $LASTEXITCODE

        # Robocopy exit codes: 0=no change, 1=files copied, 2=extras, 4=mismatches,
        # 8=failures, 16=fatal. < 4 is clean; < 8 is warning; >= 8 is error.
        $level = if ($roboExit -lt 4) { 'Success' } elseif ($roboExit -lt 8) { 'Warn' } else { 'Error' }
        Write-SOKLog "  robocopy exit $roboExit ($srcName) — $logFile" -Level $level

        if ($roboExit -ge 8) { $totalFailed++; $allVerified = $false; continue }

        # Verification: compare source vs dest file count and size
        if (-not $DryRun -and (Test-Path $destPath)) {
            try {
                $fo = [System.IO.EnumerationOptions]::new(); $fo.IgnoreInaccessible = $true; $fo.RecurseSubdirectories = $true
                $srcFiles = @([System.IO.Directory]::EnumerateFiles($src, '*', $fo))
                $dstFiles = @([System.IO.Directory]::EnumerateFiles($destPath, '*', $fo))
                $srcSize  = ($srcFiles | ForEach-Object { try { (New-Object System.IO.FileInfo($_)).Length } catch { 0 } } | Measure-Object -Sum).Sum
                $dstSize  = ($dstFiles | ForEach-Object { try { (New-Object System.IO.FileInfo($_)).Length } catch { 0 } } | Measure-Object -Sum).Sum
                $countDelta = [math]::Abs($srcFiles.Count - $dstFiles.Count)
                $sizeDeltaPct = if ($srcSize -gt 0) { [math]::Abs(($srcSize - $dstSize) / $srcSize * 100) } else { 0 }
                $verified = ($countDelta -le 5 -and $sizeDeltaPct -le 1.0)
                if ($verified) {
                    Write-SOKLog "  Verified: $($srcFiles.Count) files, $([math]::Round($srcSize/1MB,1)) MB" -Level Success
                    $totalCopied += $srcFiles.Count
                } else {
                    Write-SOKLog "  WARN: verification delta — files: $countDelta, size: $([math]::Round($sizeDeltaPct,2))%" -Level Warn
                    $allVerified = $false
                }
            } catch { Write-SOKLog "  Verification skipped: $_" -Level Warn }
        }
    }

    Write-SOKLog "Backup complete. Sources: $($BackupSources.Count) | Files copied: ~$totalCopied | Errors: $totalFailed | Verified: $allVerified" -Level $(if ($allVerified) {'Success'} else {'Warn'})
    Save-SOKHistory -ScriptName 'SOK-Backup' -RunData @{
        Sources=$BackupSources.Count; Incremental=$Incremental.IsPresent
        FilesCopied=$totalCopied; FailedSources=$totalFailed; Verified=$allVerified; DryRun=$DryRun.IsPresent
    }
}

# ══════════════════════════════════════════════════════════════════════════════
# [3] ARCHIVE — Stream Source Code to Versioned Flat-File Snapshot
# ══════════════════════════════════════════════════════════════════════════════
# The Archiver produces a single, versioned .txt file containing the full source
# code of the SOK toolsuite and associated scripts. This is not a binary backup —
# it is a human-readable, flat-file snapshot designed to survive scenarios where
# the backup drive, Git repository, and file system are all unavailable.
#
# THE DESIGN RATIONALE:
# - A .txt file can be pasted into any LLM context window for reconstruction
# - A .txt file can be read on any machine with any text editor
# - A .txt file can be diffed, versioned, emailed, or printed
# - The SOK-Comparator (in PAST) can diff two archives to understand what changed
#
# STREAMING DESIGN:
# The archive uses a 1MB-buffered FileStream + StreamWriter rather than PS
# string concatenation. This is because PS string concatenation for large
# archives would require O(n²) reallocations. The streaming approach keeps
# memory flat regardless of archive size.
#
# EXTENSION FILTER RATIONALE:
# Only source-code-class files are archived (ps1, py, json, md, yaml, etc.).
# Binary files (exe, dll, png, mp4) are excluded — they are what the Backup
# module handles. An archive with binary files would be unusable as a context
# snapshot and would grow without bound.
if ($Archive) {
    Write-SOKLog "━━━ [3] ARCHIVE: Source Code Snapshot ━━━" -Level Section
    Write-SOKLog "Sources: $($ArchiveSources.Count) | Output: $ArchiveOutputDir | Name: $ArchiveBaseName" -Level Ignore
    if ($DryRun) { Write-SOKLog '*** DRY RUN — manifest will be built but no file will be written ***' -Level Warn }

    # Ensure output directory exists
    if (-not (Test-Path $ArchiveOutputDir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $ArchiveOutputDir -Force | Out-Null }
        else { Write-SOKLog "[DRY] Would create: $ArchiveOutputDir" -Level Ignore }
    }

    # Auto-increment version number
    $version = 1
    while (Test-Path "$ArchiveOutputDir\${ArchiveBaseName}_v$version.txt") { $version++ }
    $targetFile = "$ArchiveOutputDir\${ArchiveBaseName}_v$version.txt"
    Write-SOKLog "Archive version: v$version -> $targetFile" -Level Ignore

    # Build manifest — find all matching source files
    $extRegex  = [regex]::new($ArchiveExtensions, [System.Text.RegularExpressions.RegexOptions]::Compiled)
    $manifest  = [System.Collections.Generic.List[System.IO.FileInfo]]::new()
    $totalSize = 0L

    foreach ($folder in $ArchiveSources) {
        if (-not (Test-Path $folder)) { Write-SOKLog "  SKIP (not found): $folder" -Level Warn; continue }
        $files = Get-ChildItem $folder -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object {
                $extRegex.IsMatch($_.Extension) -and
                $_.Name -notmatch [regex]::Escape($ArchiveBaseName)  # Exclude prior archives
            }
        foreach ($f in $files) { $manifest.Add($f); $totalSize += $f.Length }
    }

    $manifest = @($manifest | Sort-Object FullName)  # Deterministic ordering for diffs
    Write-SOKLog "Manifest: $($manifest.Count) files, $([math]::Round($totalSize/1MB,1)) MB" -Level Success

    if ($DryRun) {
        Write-SOKLog "[DRY] Would write $($manifest.Count) files to $targetFile" -Level Warn
        $manifest | Select-Object -First 20 | ForEach-Object { Write-SOKLog "  $($_.FullName)" -Level Ignore }
        if ($manifest.Count -gt 20) { Write-SOKLog "  ... and $($manifest.Count - 20) more" -Level Ignore }
    } else {
        # Stream the archive with 1MB buffer
        $utf8   = [System.Text.Encoding]::UTF8
        $stream = [System.IO.FileStream]::new($targetFile, [System.IO.FileMode]::Create, [System.IO.FileAccess]::Write, [System.IO.FileShare]::Read, 1048576)
        $writer = [System.IO.StreamWriter]::new($stream, $utf8)
        try {
            # Archive header
            $writer.WriteLine("# ══════════════════════════════════════════════════════════════════════")
            $writer.WriteLine("# SOK ARCHIVE SNAPSHOT v$version")
            $writer.WriteLine("# Generated  : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
            $writer.WriteLine("# Sources    : $($ArchiveSources -join ', ')")
            $writer.WriteLine("# File count : $($manifest.Count)")
            $writer.WriteLine("# Total size : $([math]::Round($totalSize/1MB,1)) MB")
            $writer.WriteLine("# Format     : SOK Archiver v2.1 | Diff-compatible with SOK-Comparator")
            $writer.WriteLine("# ══════════════════════════════════════════════════════════════════════")
            $writer.WriteLine("")

            # Table of contents
            $writer.WriteLine("# ── TABLE OF CONTENTS ─────────────────────────────────────────────────")
            foreach ($f in $manifest) {
                $fname   = $f.Name.PadRight(50).Substring(0,50)
                $sizeStr = "$([math]::Round($f.Length/1KB,1)) KB".PadLeft(10)
                $mod     = $f.LastWriteTime.ToString('yyyy-MM-dd HH:mm')
                $writer.WriteLine("# $fname $sizeStr  $mod")
            }
            $writer.WriteLine("")

            # File content sections
            $readErrors = 0
            foreach ($f in $manifest) {
                $writer.WriteLine("# ════════════════════════════════════════════════════════════════════════")
                $writer.WriteLine("# FILE: $($f.FullName)")
                $writer.WriteLine("# Size: $([math]::Round($f.Length/1KB,1)) KB | Modified: $($f.LastWriteTime.ToString('o')) | Attributes: $($f.Attributes)")
                $writer.WriteLine("# ════════════════════════════════════════════════════════════════════════")
                try {
                    $reader = [System.IO.StreamReader]::new($f.FullName)
                    while (($line = $reader.ReadLine()) -ne $null) { $writer.WriteLine($line) }
                    $reader.Dispose()
                } catch {
                    $writer.WriteLine("# !!! READ ERROR: $($_.Exception.Message) !!!")
                    $readErrors++
                }
                $writer.WriteLine("")
            }

            Write-SOKLog "Archive written: $targetFile ($([math]::Round((Get-Item $targetFile).Length/1MB,1)) MB) | Read errors: $readErrors" -Level $(if ($readErrors -eq 0) {'Success'} else {'Warn'})
        } finally {
            if ($writer) { $writer.Flush(); $writer.Dispose() }
            if ($stream) { $stream.Dispose() }
            [System.GC]::Collect()
        }
        Save-SOKHistory -ScriptName 'SOK-Archiver' -RunData @{
            Version=$version; FileCount=$manifest.Count; SizeBytes=$totalSize; TargetPath=$targetFile
        }
    }
}

# ══════════════════════════════════════════════════════════════════════════════
# END MODULES
# ══════════════════════════════════════════════════════════════════════════════
} catch {
    Write-SOKLog "TERMINATING ERROR in SOK-FUTURE: $_" -Level Error
} finally {
    $duration = [math]::Round(((Get-Date) - $GlobalStartTime).TotalSeconds, 1)
    Write-SOKLog "━━━ SOK-FUTURE EXECUTION COMPLETE (${duration}s) ━━━" -Level Section
    if ($DryRun) { Write-SOKLog "DRY RUN — no persistent changes were made to disk." -Level Warn }
    Write-SOKLog "The system is better protected than it was $duration seconds ago." -Level Ignore
    Write-SOKLog "Next: SOK-PAST.ps1 -TakeInventory (verify junction state) | SOK-PRESENT.ps1 -Optimize (maintain momentum)" -Level Ignore
    Save-SOKHistory -ScriptName 'SOK-FUTURE' -RunData @{ Modules=$ActiveModules; DurationSec=$duration; DryRun=$DryRun.IsPresent }
}
