<#
.SYNOPSIS
    Restoration utility to undo backup operations using generated file maps.

.DESCRIPTION
    Companion script to Backup-FilesAdvanced.ps1 that restores files to their original 
    locations using the file map JSON generated during backup. Handles drive letter changes,
    conflict resolution, and comprehensive error logging.

.PARAMETER FileMapPath
    Path to the FileMap JSON file generated during backup operation.

.PARAMETER DryRun
    Preview restoration without actually moving files.

.PARAMETER DriveLetterMapping
    Hashtable for drive letter changes (e.g., @{'D:' = 'E:'; 'C:' = 'F:'})

.EXAMPLE
    .\Restore-FilesFromBackup.ps1 -FileMapPath "D:\Backup\FileMap_20260109_143022.json"
    Restores files using the file map

.EXAMPLE
    .\Restore-FilesFromBackup.ps1 -FileMapPath "D:\Backup\FileMap_20260109_143022.json" -DryRun
    Preview restoration without executing

.EXAMPLE
    $mapping = @{'D:' = 'E:'}
    .\Restore-FilesFromBackup.ps1 -FileMapPath "E:\Backup\FileMap_20260109_143022.json" -DriveLetterMapping $mapping
    Restores with drive letter remapping

.NOTES
    Author: AI Engineer & PowerShell Expert
    Version: 2.0
    Last Updated: 2026-01-09
    
    This script is designed to work with the file maps generated by Backup-FilesAdvanced.ps1
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, HelpMessage="Path to the FileMap JSON file")]
    [ValidateScript({Test-Path $_ -PathType Leaf})]
    [string]$FileMapPath,

    [Parameter(Mandatory=$false, HelpMessage="Preview without executing")]
    [switch]$DryRun,

    [Parameter(Mandatory=$false, HelpMessage="Drive letter mapping for changed drives")]
    [hashtable]$DriveLetterMapping = @{}
)

#region ASCII Art

function Show-RestorationArt {
    $art = @"

    ╔════════════════════════════════════════════════════════════════════════╗
    ║                                                                        ║
    ║                   ✦ FILE RESTORATION UTILITY ✦                        ║
    ║                                                                        ║
    ║                           .:*~*:._.:*~*:.                             ║
    ║                      .:*'    ↺ RESTORE ↺    '*:.                      ║
    ║                   .:*'     ╱───────────╲     '*:.                     ║
    ║                .:*'       │   ⟲ TIME ⟳   │       '*:.                 ║
    ║             .:*'          │   REVERSAL   │          '*:.              ║
    ║          .:*'             ╲───────────╱             '*:.             ║
    ║        .*'      ◄─────────────────────────────►      '*.             ║
    ║       *    ╔═══════════════════════════════════╗    *                ║
    ║      ✦     ║  RETURNING FILES TO ORIGIN       ║     ✦               ║
    ║     ✦      ╚═══════════════════════════════════╝      ✦              ║
    ║    ✦          ↙              ↓              ↘          ✦             ║
    ║     ✦       [SRC]          [MAP]          [DEST]       ✦              ║
    ║      ✦        ↖              ↑              ↗        ✦               ║
    ║       *    ╔═══════════════════════════════════╗    *                ║
    ║        '*  ║  SACRED GEOMETRY OF RECOVERY     ║  *'                  ║
    ║          '╚═══════════════════════════════════╝'                      ║
    ║                                                                        ║
    ║              Restoring Order to Digital Chaos                         ║
    ║                                                                        ║
    ╚════════════════════════════════════════════════════════════════════════╝

"@
    
    Write-Host $art -ForegroundColor Green
    Start-Sleep -Milliseconds 1500
}

#endregion

#region Helper Functions

function Initialize-RestorationLog {
    param([string]$LogPath)
    
    $logHeader = @"
╔════════════════════════════════════════════════════════════════════════╗
║                    RESTORATION OPERATION LOG                           ║
║                    $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')                          ║
╚════════════════════════════════════════════════════════════════════════╝

"@
    
    Set-Content -Path $LogPath -Value $logHeader -Force
    return $LogPath
}

function Write-RestoreLog {
    param(
        [string]$Message,
        [ValidateSet('Info', 'Warning', 'Error', 'Success', 'Header', 'Stat')]
        [string]$Level = 'Info',
        [string]$LogPath
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    
    switch ($Level) {
        'Info'    { Write-Host $logMessage -ForegroundColor Cyan }
        'Warning' { Write-Host $logMessage -ForegroundColor Yellow }
        'Error'   { Write-Host $logMessage -ForegroundColor Red }
        'Success' { Write-Host $logMessage -ForegroundColor Green }
        'Header'  { Write-Host "`n$Message" -ForegroundColor Magenta }
        'Stat'    { Write-Host $Message -ForegroundColor White }
    }
    
    Add-Content -Path $LogPath -Value $logMessage
}

function Remap-DriveLetter {
    param(
        [string]$Path,
        [hashtable]$Mapping
    )
    
    if ($Mapping.Count -eq 0) {
        return $Path
    }
    
    $drive = Split-Path $Path -Qualifier
    
    if ($Mapping.ContainsKey($drive)) {
        $newDrive = $Mapping[$drive]
        $pathWithoutDrive = $Path.Substring($drive.Length)
        return $newDrive + $pathWithoutDrive
    }
    
    return $Path
}

function Test-PathCoherence {
    param(
        [string]$SourcePath,
        [string]$DestinationPath
    )
    
    $issues = @()
    
    # Check if source exists
    if (-not (Test-Path $SourcePath)) {
        $issues += "Source file does not exist: $SourcePath"
    }
    
    # Check if destination directory would be valid
    $destDir = Split-Path $DestinationPath -Parent
    $destDrive = Split-Path $DestinationPath -Qualifier
    
    if ($destDrive -and -not (Test-Path $destDrive)) {
        $issues += "Destination drive does not exist: $destDrive"
    }
    
    # Check for path length
    if ($DestinationPath.Length -gt 260) {
        $issues += "Destination path exceeds maximum length (260 chars): $DestinationPath"
    }
    
    return $issues
}

function Get-DriveLetterChanges {
    Write-Host "`n╔════════════════════════════════════════════════════════╗" -ForegroundColor Yellow
    Write-Host "║          DRIVE LETTER CHANGE DETECTION                ║" -ForegroundColor Yellow
    Write-Host "╚════════════════════════════════════════════════════════╝`n" -ForegroundColor Yellow
    
    Write-Host "Have any drive letters changed since the backup? (Y/N): " -NoNewline -ForegroundColor Cyan
    $response = Read-Host
    
    if ($response -eq 'Y' -or $response -eq 'y') {
        $mapping = @{}
        
        Write-Host "`nEnter drive letter mappings (press Enter when done):" -ForegroundColor Yellow
        Write-Host "Format: OldDrive NewDrive (e.g., 'D: E:')" -ForegroundColor DarkGray
        
        while ($true) {
            Write-Host "`nMapping (or press Enter to finish): " -NoNewline -ForegroundColor Cyan
            $input = Read-Host
            
            if ([string]::IsNullOrWhiteSpace($input)) {
                break
            }
            
            $parts = $input -split '\s+'
            if ($parts.Count -eq 2) {
                $oldDrive = $parts[0].ToUpper()
                $newDrive = $parts[1].ToUpper()
                
                # Ensure format is correct
                if (-not $oldDrive.EndsWith(':')) { $oldDrive += ':' }
                if (-not $newDrive.EndsWith(':')) { $newDrive += ':' }
                
                $mapping[$oldDrive] = $newDrive
                Write-Host "  Added mapping: $oldDrive -> $newDrive" -ForegroundColor Green
            } else {
                Write-Host "  Invalid format. Use: OldDrive NewDrive" -ForegroundColor Red
            }
        }
        
        return $mapping
    }
    
    return @{}
}

#endregion

#region Main Restoration Logic

try {
    # Display restoration art
    Show-RestorationArt
    
    # Initialize log
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $logDir = Split-Path $FileMapPath -Parent
    $logPath = Join-Path $logDir "RestorationLog_${timestamp}.log"
    $logPath = Initialize-RestorationLog -LogPath $logPath
    
    Write-RestoreLog "╔════════════════════════════════════════════════════════════════════════╗" -Level Header -LogPath $logPath
    Write-RestoreLog "║                    RESTORATION INITIALIZATION                          ║" -Level Header -LogPath $logPath
    Write-RestoreLog "╚════════════════════════════════════════════════════════════════════════╝" -Level Header -LogPath $logPath
    
    Write-RestoreLog "File Map: $FileMapPath" -Level Info -LogPath $logPath
    Write-RestoreLog "Dry Run: $DryRun" -Level Info -LogPath $logPath
    
    # Check for drive letter changes if not provided
    if ($DriveLetterMapping.Count -eq 0) {
        $DriveLetterMapping = Get-DriveLetterChanges
    }
    
    if ($DriveLetterMapping.Count -gt 0) {
        Write-RestoreLog "`nDrive Letter Mappings:" -Level Header -LogPath $logPath
        foreach ($mapping in $DriveLetterMapping.GetEnumerator()) {
            Write-RestoreLog "  $($mapping.Key) -> $($mapping.Value)" -Level Stat -LogPath $logPath
        }
    }
    
    # Load file map
    Write-RestoreLog "`nLoading file map..." -Level Info -LogPath $logPath
    $fileMap = Get-Content $FileMapPath | ConvertFrom-Json
    
    Write-RestoreLog "Loaded $($fileMap.Count) file entries" -Level Success -LogPath $logPath
    
    # Validate and categorize files
    Write-RestoreLog "`nValidating file paths..." -Level Info -LogPath $logPath
    
    $validFiles = @()
    $invalidFiles = @()
    $coherenceIssues = @()
    
    foreach ($entry in $fileMap) {
        $sourcePath = Remap-DriveLetter -Path $entry.DestinationPath -Mapping $DriveLetterMapping
        $destPath = Remap-DriveLetter -Path $entry.SourcePath -Mapping $DriveLetterMapping
        
        $issues = Test-PathCoherence -SourcePath $sourcePath -DestinationPath $destPath
        
        if ($issues.Count -eq 0) {
            $validFiles += @{
                Source = $sourcePath
                Destination = $destPath
                Size = $entry.Size
                OriginalEntry = $entry
            }
        } else {
            $invalidFiles += @{
                Source = $sourcePath
                Destination = $destPath
                Issues = $issues
                OriginalEntry = $entry
            }
            
            foreach ($issue in $issues) {
                $coherenceIssues += @{
                    File = $destPath
                    Issue = $issue
                    Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                }
            }
        }
    }
    
    Write-RestoreLog "Valid files: $($validFiles.Count)" -Level Success -LogPath $logPath
    Write-RestoreLog "Invalid/problematic files: $($invalidFiles.Count)" -Level Warning -LogPath $logPath
    
    if ($coherenceIssues.Count -gt 0) {
        Write-RestoreLog "`nCoherence issues detected:" -Level Warning -LogPath $logPath
        foreach ($issue in $coherenceIssues) {
            Write-RestoreLog "  $($issue.Issue)" -Level Warning -LogPath $logPath
        }
    }
    
    # Statistics
    $stats = @{
        TotalFiles = $validFiles.Count
        Processed = 0
        Success = 0
        Failed = 0
        Skipped = 0
    }
    
    $failedRestorations = @()
    $heinousIssues = @()
    
    if ($DryRun) {
        Write-RestoreLog "`n╔════════════════════════════════════════════════════════════════════════╗" -Level Header -LogPath $logPath
        Write-RestoreLog "║                    DRY RUN - NO FILES WILL BE MOVED                    ║" -Level Header -LogPath $logPath
        Write-RestoreLog "╚════════════════════════════════════════════════════════════════════════╝" -Level Header -LogPath $logPath
    } else {
        Write-RestoreLog "`n╔════════════════════════════════════════════════════════════════════════╗" -Level Header -LogPath $logPath
        Write-RestoreLog "║                    BEGINNING RESTORATION                               ║" -Level Header -LogPath $logPath
        Write-RestoreLog "╚════════════════════════════════════════════════════════════════════════╝" -Level Header -LogPath $logPath
    }
    
    # Process valid files
    foreach ($file in $validFiles) {
        $stats.Processed++
        $percentComplete = [math]::Round(($stats.Processed / $stats.TotalFiles) * 100, 2)
        
        Write-Progress -Activity "Restoring Files" `
                       -Status "File $($stats.Processed) of $($stats.TotalFiles) | $percentComplete%" `
                       -PercentComplete $percentComplete `
                       -CurrentOperation "Processing: $($file.Destination)"
        
        try {
            # Verify source exists
            if (-not (Test-Path $file.Source)) {
                throw "Source file not found: $($file.Source)"
            }
            
            # Create destination directory
            $destDir = Split-Path $file.Destination -Parent
            
            if (-not $DryRun) {
                if (-not (Test-Path $destDir)) {
                    New-Item -Path $destDir -ItemType Directory -Force
                }
            }
            
            # Check for conflicts
            if (Test-Path $file.Destination) {
                Write-RestoreLog "WARNING: Destination already exists, will overwrite: $($file.Destination)" -Level Warning -LogPath $logPath
            }
            
            # Perform move
            if (-not $DryRun) {
                Move-Item -Path $file.Source -Destination $file.Destination -Force
            }
            
            $stats.Success++
            Write-RestoreLog "Restored: $($file.Source) -> $($file.Destination)" -Level Success -LogPath $logPath
            
        } catch {
            $stats.Failed++
            $failedRestorations += @{
                SourcePath = $file.Source
                DestinationPath = $file.Destination
                Error = $_.Exception.Message
                Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
            }
            Write-RestoreLog "FAILED: $($file.Destination) - $($_.Exception.Message)" -Level Error -LogPath $logPath
            
            # Track heinous issues
            if ($_.Exception.Message -match "access.*denied|permission|locked|in use") {
                $heinousIssues += @{
                    Type = "Permission/Lock Issue"
                    File = $file.Destination
                    Error = $_.Exception.Message
                }
            } elseif ($_.Exception.Message -match "path.*long|exceeds") {
                $heinousIssues += @{
                    Type = "Path Length Issue"
                    File = $file.Destination
                    Error = $_.Exception.Message
                }
            } elseif ($_.Exception.Message -match "not found|does not exist") {
                $heinousIssues += @{
                    Type = "Missing File Issue"
                    File = $file.Destination
                    Error = $_.Exception.Message
                }
            }
        }
    }
    
    Write-Progress -Activity "Restoring Files" -Completed
    
    # Generate summary
    Write-RestoreLog "`n╔════════════════════════════════════════════════════════════════════════╗" -Level Header -LogPath $logPath
    Write-RestoreLog "║                    RESTORATION SUMMARY                                 ║" -Level Header -LogPath $logPath
    Write-RestoreLog "╚════════════════════════════════════════════════════════════════════════╝" -Level Header -LogPath $logPath
    
    Write-RestoreLog "Total valid files: $($stats.TotalFiles)" -Level Stat -LogPath $logPath
    Write-RestoreLog "Successfully restored: $($stats.Success)" -Level Success -LogPath $logPath
    Write-RestoreLog "Failed: $($stats.Failed)" -Level $(if ($stats.Failed -gt 0) { 'Error' } else { 'Info' }) -LogPath $logPath
    Write-RestoreLog "Invalid/skipped: $($invalidFiles.Count)" -Level Warning -LogPath $logPath
    
    # Export failed restorations
    if ($failedRestorations.Count -gt 0) {
        $failedPath = Join-Path $logDir "FailedRestorations_${timestamp}.txt"
        
        $failedContent = "FAILED RESTORATION OPERATIONS`n"
        $failedContent += "=" * 80 + "`n`n"
        
        foreach ($failed in $failedRestorations) {
            $failedContent += "Source: $($failed.SourcePath)`n"
            $failedContent += "Destination: $($failed.DestinationPath)`n"
            $failedContent += "Error: $($failed.Error)`n"
            $failedContent += "Timestamp: $($failed.Timestamp)`n"
            $failedContent += "-" * 80 + "`n`n"
        }
        
        Set-Content -Path $failedPath -Value $failedContent
        Write-RestoreLog "`nFailed restorations documented in: $failedPath" -Level Error -LogPath $logPath
    }
    
    # Export invalid files
    if ($invalidFiles.Count -gt 0) {
        $invalidPath = Join-Path $logDir "InvalidFiles_${timestamp}.txt"
        
        $invalidContent = "FILES THAT COULD NOT BE RESTORED`n"
        $invalidContent += "=" * 80 + "`n`n"
        
        foreach ($invalid in $invalidFiles) {
            $invalidContent += "Intended Destination: $($invalid.Destination)`n"
            $invalidContent += "Current Location: $($invalid.Source)`n"
            $invalidContent += "Issues:`n"
            foreach ($issue in $invalid.Issues) {
                $invalidContent += "  - $issue`n"
            }
            $invalidContent += "-" * 80 + "`n`n"
        }
        
        Set-Content -Path $invalidPath -Value $invalidContent
        Write-RestoreLog "Invalid files documented in: $invalidPath" -Level Warning -LogPath $logPath
    }
    
    # Export heinous issues
    if ($heinousIssues.Count -gt 0) {
        $heinousPath = Join-Path $logDir "HeinousIssues_${timestamp}.txt"
        
        $heinousContent = "ESPECIALLY PROBLEMATIC FILES AND ISSUES`n"
        $heinousContent += "=" * 80 + "`n`n"
        
        # Group by type
        $grouped = $heinousIssues | Group-Object -Property Type
        
        foreach ($group in $grouped) {
            $heinousContent += "`n$($group.Name) ($($group.Count) files):`n"
            $heinousContent += "-" * 80 + "`n"
            
            foreach ($item in $group.Group) {
                $heinousContent += "File: $($item.File)`n"
                $heinousContent += "Error: $($item.Error)`n`n"
            }
        }
        
        Set-Content -Path $heinousPath -Value $heinousContent
        Write-RestoreLog "`nHeinous issues documented in: $heinousPath" -Level Error -LogPath $logPath
    }
    
    # Export absolute paths of unrestored files
    $unresto redFiles = $invalidFiles + $failedRestorations
    if ($unrestoredFiles.Count -gt 0) {
        $unrestoredPath = Join-Path $logDir "UnrestoredAbsolutePaths_${timestamp}.txt"
        
        $unrestoredContent = "ABSOLUTE PATHS OF UNRESTORED FILES`n"
        $unrestoredContent += "=" * 80 + "`n`n"
        $unrestoredContent += "Current Locations (where files remain):`n"
        $unrestoredContent += "-" * 80 + "`n"
        
        foreach ($file in $unrestoredFiles) {
            if ($file.Source) {
                $unrestoredContent += "$($file.Source)`n"
            } elseif ($file.SourcePath) {
                $unrestoredContent += "$($file.SourcePath)`n"
            }
        }
        
        $unrestoredContent += "`n`nIntended Destinations (where files should have gone):`n"
        $unrestoredContent += "-" * 80 + "`n"
        
        foreach ($file in $unrestoredFiles) {
            if ($file.Destination) {
                $unrestoredContent += "$($file.Destination)`n"
            } elseif ($file.DestinationPath) {
                $unrestoredContent += "$($file.DestinationPath)`n"
            }
        }
        
        Set-Content -Path $unrestoredPath -Value $unrestoredContent
        Write-RestoreLog "Unrestored file paths documented in: $unrestoredPath" -Level Warning -LogPath $logPath
    }
    
    Write-RestoreLog "`n════════════════════════════════════════════════════════════════════════" -Level Header -LogPath $logPath
    Write-RestoreLog "RESTORATION OPERATION COMPLETED" -Level Success -LogPath $logPath
    Write-RestoreLog "════════════════════════════════════════════════════════════════════════" -Level Header -LogPath $logPath
    Write-RestoreLog "Log file: $logPath" -Level Info -LogPath $logPath
    
} catch {
    Write-RestoreLog "CRITICAL ERROR: $($_.Exception.Message)" -Level Error -LogPath $logPath
    Write-RestoreLog "Stack Trace: $($_.ScriptStackTrace)" -Level Error -LogPath $logPath
    throw
}

#endregion
